In [44]:
import numpy as np
import pandas as pd
%matplotlib inline
import os

import xgboost as xgb
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.metrics import cohen_kappa_score

In [28]:
import platform
if platform.system()=='Windows':
    path0 = 'r\'./'
    #slash = '\\'
else:
    path0 = "\'../"
    #slash = "/"
    
print(path0)#,slash)

r'./

In [31]:
train_df = pd.read_csv(r'./input/petfinder-adoption-prediction/train/train.csv')
test_df = pd.read_csv(r'./input/petfinder-adoption-prediction/test/test.csv')

def metric(y1,y2): 
    return cohen_kappa_score(y1,y2, weights='quadratic') #Quadratic Weigthed Kappa

In [32]:
train_df.describe()

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,VideoAmt,PhotoAmt,AdoptionSpeed
count,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000,14993.000000
mean,1.457614,10.452078,265.272594,74.009738,1.776162,2.234176,3.222837,1.882012,1.862002,1.467485,1.731208,1.558727,1.914227,1.036617,1.576069,21.259988,41346.028347,0.056760,3.889215,2.516441
std,0.498217,18.155790,60.056818,123.011575,0.681592,1.745225,2.742562,2.984086,0.547959,0.599070,0.667649,0.695817,0.566172,0.199535,1.472477,78.414548,32.444153,0.346185,3.487810,1.177265
min,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,41324.000000,0.000000,0.000000,0.000000
25%,1.000000,2.000000,265.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,0.000000,41326.000000,0.000000,2.000000,2.000000
50%,1.000000,3.000000,266.000000,0.000000,2.000000,2.000000,2.000000,0.000000,2.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,0.000000,41326.000000,0.000000,3.000000,2.000000
75%,2.000000,12.000000,307.000000,179.000000,2.000000,3.000000,6.000000,5.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,0.000000,41401.000000,0.000000,5.000000,4.000000
max,2.000000,255.000000,307.000000,307.000000,3.000000,7.000000,7.000000,7.000000,4.000000,3.000000,3.000000,3.000000,3.000000,3.000000,20.000000,3000.000000,41415.000000,8.000000,30.000000,4.000000

In [33]:
train_df.head()

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,...,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,...,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,...,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,...,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,...,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

In [34]:
def xgb_progressbar(rounds=1000):
    """Progressbar for xgboost using tqdm library.
 
    Examples
    --------
 
    >>> model = xgb.train(params, X_train, 1000, callbacks=[xgb_progress(1000), ])
    """
    pbar = tqdm(total=rounds)
 
    def callback(_, ):
        pbar.update(1)
 
    return callback

In [37]:
!pip install opencv

Collecting opencv

  Could not find a version that satisfies the requirement opencv (from versions: )
No matching distribution found for opencv

In [45]:
import cv2
import pandas as pd
import numpy as np
import os
from tqdm import tqdm, tqdm_notebook
from keras.applications.densenet import preprocess_input, DenseNet121, DenseNet169

#train_df = pd.read_csv('../input/petfinder-adoption-prediction/train/train.csv')
img_size = 256
batch_size = 16
pet_ids = train_df['PetID'].values
n_batches = len(pet_ids) // batch_size + 1

def resize_to_square(im):
    old_size = im.shape[:2] # old_size is in (height, width) format
    ratio = float(img_size)/max(old_size)
    new_size = tuple([int(x*ratio) for x in old_size])
    # new_size should be in (width, height) format
    im = cv2.resize(im, (new_size[1], new_size[0]))
    delta_w = img_size - new_size[1]
    delta_h = img_size - new_size[0]
    top, bottom = delta_h//2, delta_h-(delta_h//2)
    left, right = delta_w//2, delta_w-(delta_w//2)
    color = [0, 0, 0]
    new_im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT,value=color)
    return new_im

def load_image(path, pet_id):
    image = cv2.imread(f'{path}{pet_id}-1.jpg')
    new_image = resize_to_square(image)
    new_image = preprocess_input(new_image)
    return new_image

In [40]:
from keras.models import Model
from keras.layers import GlobalAveragePooling2D, Input, Lambda, AveragePooling1D
import keras.backend as K
inp = Input((256,256,3))
backbone = DenseNet121(
    #weights = r'./input/keras-applications-weights/densenet169_weights_tf_dim_ordering_tf_kernels_notop.h5',
    input_tensor = inp, include_top = False)
print("done")
x = backbone.output
x = GlobalAveragePooling2D()(x)
x = Lambda(lambda x: K.expand_dims(x,axis = -1))(x)
x = AveragePooling1D(4)(x)
out = Lambda(lambda x: x[:,:,0])(x)

m = Model(inp,out)

Downloading data from https://github.com/keras-team/keras-applications/releases/download/densenet/densenet121_weights_tf_dim_ordering_tf_kernels_notop.h5
29089792/29084464 [==============================] - ETA: 12:0 - ETA: 8:0 - ETA: 7: - ETA: 6: - ETA: 6: - ETA: 5: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 6: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 7: - ETA: 6: - ETA: 6: - ETA: 6: - ETA: 6: - ETA: 6: - ETA: 6: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 4: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 5: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 4: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 58s - ETA: 57 - ETA: 56 - ETA: 55 - ETA: 54 - ETA: 52 - ETA: 51 - ETA: 50 - ETA: 49 - ETA: 47 - ETA: 46 - ETA: 45 - ETA: 44 - ETA: 42 - ETA: 42 - ETA: 40 - ETA: 40 - ETA: 38 - ETA: 37 - ETA: 36 - ETA: 35 - ETA: 35 - ETA: 33 - ETA: 33 - ETA: 32 - ETA: 31 - ETA: 30 - ETA: 29 - ETA: 28 - ETA: 27 - ETA: 27 - ETA: 26 - ETA: 25 - ETA: 24 - ETA: 23 - ETA: 22 - ETA: 22 - ETA: 21 - ETA: 20 - ETA: 20 - ETA: 19 - ETA: 18 - ETA: 18 - ETA: 17 - ETA: 16 - ETA: 16 - ETA: 15 - ETA: 15 - ETA: 14 - ETA: 13 - ETA: 13 - ETA: 12 - ETA: 12 - ETA: 11 - ETA: 11 - ETA: 10 - ETA: 9 - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - 26s 1us/step
done

In [47]:
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

In [53]:
features = {}
for b in tqdm(range(n_batches)):
    start = b*batch_size
    end = (b+1)*batch_size
    batch_pets = pet_ids[start:end]
    batch_images = np.zeros((len(batch_pets),img_size,img_size,3))
    #print(b)
    for i,pet_id in enumerate(batch_pets):
        try:
            batch_images[i] = load_image(r'./input/petfinder-adoption-prediction/train_images/', pet_id)
        except:
            pass
    batch_preds = m.predict(batch_images)
    for i,pet_id in enumerate(batch_pets):
        features[pet_id] = batch_preds[i]

100%|██████████| 938/938 [2:56:08<00:00,  7.71s/it]

In [54]:
train_feats = pd.DataFrame.from_dict(features, orient='index')
train_feats.to_csv('train_img_features.csv')
train_feats.head()

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
86e1089a3,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
6296e909a,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
3422e4906,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
5842f1ff5,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
850a43f90,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685

In [55]:

n_batches = len(test_df['PetID'].values) // batch_size + 1
features = {}
for b in tqdm(range(n_batches)):
    start = b*batch_size
    end = (b+1)*batch_size
    batch_pets = pet_ids[start:end]
    batch_images = np.zeros((len(batch_pets),img_size,img_size,3))
    #print(b)
    for i,pet_id in enumerate(batch_pets):
        try:
            batch_images[i] = load_image("../input/petfinder-adoption-prediction/test_images/", pet_id)
        except:
            pass
    batch_preds = m.predict(batch_images)
    for i,pet_id in enumerate(batch_pets):
        features[pet_id] = batch_preds[i]
test_feats = pd.DataFrame.from_dict(features, orient='index')
test_feats.to_csv('test_img_features.csv')
test_feats.head()

100%|██████████| 247/247 [44:46<00:00, 10.85s/it]

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
86e1089a3,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
6296e909a,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
3422e4906,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
5842f1ff5,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
850a43f90,0.001913,0.200123,0.034662,0.011279,0.22124,0.002751,0.001853,0.004002,0.114432,0.029524,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685

In [56]:
tab_imfeatures = pd.concat([train_df, train_feats.reset_index(drop=True)], axis=1,sort=False)
train_df = tab_imfeatures

tab_imfeatures2 = pd.concat([test_df, test_feats.reset_index(drop=True)], axis=1,sort=False)
test_df = tab_imfeatures2

In [57]:
train_df.head()

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,246,247,248,249,250,251,252,253,254,255
0,2,Nibble,3,299,0,1,1,7,0,1,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
1,2,No Name Yet,1,265,0,1,1,2,0,2,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
2,1,Brisco,1,307,0,1,2,7,0,2,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
3,1,Miko,4,307,0,2,1,2,0,2,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685
4,1,Hunter,1,307,0,1,1,0,0,2,...,0.017692,0.004894,0.045289,0.03007,0.013002,0.045237,0.051465,0.071165,0.063994,0.055685

In [ ]:
permuted = train_df.reindex(np.random.permutation(train_df.index))
ytrain = permuted['AdoptionSpeed']
clean_train = permuted.drop(columns=['Name', 'RescuerID', 'Description', 'PetID', 'AdoptionSpeed'])
clean_test = test_df.drop(columns=['Name', 'RescuerID', 'Description', 'PetID'])

df_columns = clean_train.columns
num_train = len(clean_train)

x_train = clean_train[:num_train//10*9]
y_train = ytrain[:num_train//10*9]
x_val = clean_train[num_train//10*9:]
y_val = ytrain[num_train//10*9:]
print(df_columns)
dtrain = xgb.DMatrix(x_train.values, y_train.values)#, feature_names=df_columns)
dval = xgb.DMatrix(x_val.values)#, feature_names=df_columns)
dtest = xgb.DMatrix(clean_test.values)#, feature_names=df_columns)

In [5]:
#настраиваем XGBoost
xgb_params = {'subsample': 0.6, 'n_estimators': 300, 'min_child_weight': 5, 
              'max_depth': 7, 'learning_rate': 0.03, 'gamma': 2, 'num_class':5,
              'colsample_bytree': 1.0, 'objective':'multi:softmax'}
def kappa(y1,y2): 
    score = cohen_kappa_score(y1,y2, weights='quadratic')
    return 'kappa', score


num_boost_round=500

In [6]:
num_boost_round=500
model = xgb.train( dict(xgb_params),#subsample=0.9, n_estimators=500, min_child_weight=2, 
                           #max_depth=7, learning_rate=0.03, gamma=2, colsample_bytree=0.8),
                  dtrain,feval=kappa, maximize=True,
                   num_boost_round=num_boost_round,verbose_eval=False, callbacks=[xgb_progressbar(num_boost_round)])

NameError: name 'dtrain' is not defined

In [ ]:
val_pred=model.predict(dval).astype(int)
metric(val_pred, y_val.values)

In [ ]:

test_pred=np.round(model.predict(dtest)).astype(int)
print(test_pred.max())
submit_df = pd.DataFrame(data={"PetID" : test_df["PetID"], 
                                   "AdoptionSpeed" : test_pred})
submit_df.to_csv("submission.csv", index=False)
submit_df.head()

In [59]:
list(range(3))

[0, 1, 2]

In [64]:
load_image(r'./input/petfinder-adoption-prediction/train_images/', '86e1089a3')

AttributeError: 'NoneType' object has no attribute 'shape'